apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen 1234;
      location / {
        root /usr/share/nginx/html;
        index index.html;
      }
    }
